version: '3'
services:
  nginx:
    image: forum-nginx
    ports:
      - 80:80
    depends_on:
      - forum
    networks:
      - app-network
  forum:
    image: forum
    ports:
      - 9000:9000
    volumes:
      - ./src/.:/var/www/forum
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: forum-mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: forum
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge

